baseURL = "https://ppsreejith.net"
languageCode = "en-us"
title = "Dot Asterisk"
theme = "yinyang"

[params]
headTitle = "Dot Asterisk"
mainSections = ["posts"]

[[params.socials]]
name = "Github"
link = "https://github.com/ppsreejith"