#+hugo_base_dir: ../
#+date: <2020-07-12 Sun>
#+hugo_tags: personal goals meta
#+hugo_categories: meta
#+TITLE: 30 Days of Writing

  Today marks my 30 day writing streak.

  I'd set myself this OKR (along with 2 others) at the start of June. My plan is to cover all my OKRs in 3 months, i.e. by 1st September.

  From writing tips like "Write drunk, edit sober" to the discipline needed to write everyday, I've learned a lot over the past month. However, it has not been easy. I'll consider future OKRs more seriously knowing how time consuming this ended up being. Another thing that's helped is using this blog as a [[https://www.nateliason.com/blog/self-education][sandbox]] to learn how to write better.

  I did this by reading and applying [[https://www.goodreads.com/book/show/53343.On_Writing_Well][On Writing Well]] whilst writing. I've come to appreciate this mode of learning greatly. In the book [[https://www.goodreads.com/book/show/1875338.The_Wisdom_Paradox][The Wisdom Paradox]], Goldberg points out that there are 2 kinds of memory. The procedural, i.e. the knowledge of how, and the declarative, i.e. the what. I'd like to think of it as the difference between knowing the facts vs having the experience. It feels /completely/ different. Applying the sandbox method allowed me to gain quick [[file:feedback-and-magic.org][feedback]] on what I learned whilst allowing me to read the book with a fresh context of the problems the author is talking about.

  This writing streak also helped me test out my [[https://notes.ppsreejith.net][note-taking system]] which I'd [[file:book-review:-how-to-take-smart-notes.org][written about]] earlier. Using these notes to write articles allowed me to appreciate good notes and understand how to take better ones. For example, I've found that putting tags at the top of a note impedes my ability to interpret how the tag is relevant to that note when searching by tag. To me, the value of a note comes from it being self contained and being easily parsed using backlinks from other articles.

  Overall, this has been a valuable exercise. I've gained a valuable writing process, a few crucial skills, and the confidence to write more articles. My vision is to use Dot Asterisk as a medium and sandbox to express myself better. Writing will be a core component of this vision but I plan to try out [[file:thoughts-on-dot-asterisk.org][other techniques]] too.
