#+hugo_base_dir: ../
#+date: <2020-07-03 Fri>
#+hugo_tags: review fitness personal
#+hugo_categories: fitness
#+TITLE: 6 Hour Fitness

  I've adopted a regimen where I work out less than 6 hours a month.

  I consider it a bit simpler than the 4 hour body by Tim Ferriss. Based on [[https://twitter.com/Mangan150][P.D. Mangan's]] book [[https://gumroad.com/l/eJdSs][1 hour fitness]], it's a combination of weight training and high intensity sprint interval training.

  Weight training involves just 1 set of zero momentum reps of compound barbell exercises done to failure. I do deadlifts, squats, bench presses, overhead presses and some, more focused, routines. To achieve failure, I use drop sets. i.e. Switching to lower weights when I cannot do one more rep. This allows me to achieve failure quickly. I do 2 sessions a week at 20 minutes per session.

  Mangan argues that there's [[https://www.researchgate.net/publication/228830087_Evidence-Based_Resistance_Training_Recommendations][little evidence]] that performing more than 1 set of each exercise leads to increase in muscle growth if that 1 set is done to failure.

  The other major workout I do is sprint interval training or HIIT sprints. The way I do it, I run 30 seconds at full speed and rest for 30 seconds. I repeat this for 7 reps (My current limit). This exercise packs a wallop and I've increased my limit from 3 to 7 reps over the last 3 months. To be fair, I'm still [[file:on-tinkering.org][tinkering]] with my technique as finding information on the ideal way to do this has been surprisingly difficult. I do 2 sessions a week at 20 minutes per session (including warm up and cool down)

  On a similar vein, Taleb (who is also a weight training practitioner) argues that our bodies (and bodies of all animals) [[https://medium.com/@nntaleb/strength-training-is-learning-from-tail-events-7aa2c074569d][should be seen as risk management systems]] meant to handle our environment, learning disproportionately from extremes. I find this a fascinating take on the primacy of survival for organisms and a useful mental model of the human body. The article is worth a read and aligns well with the ideas of Mangan's ideas of subjecting your body to extremes.

  Another reason I like weight training and HIIT sprints is that they are forms of [[https://startingstrength.com/article/training_vs_exercise][training rather than exercise]]. Which means that when you do it every week, you also level up. i.e. your ability improves with time. In weight training, this involves lifting heavier weights. In sprint interval training, this involves running longer bouts or more extreme intervals.

  This routine has worked out really well for me. As part of this, I've also built up a home training setup collecting cheap weight plates. From my calculations, it cost me less than what a premium gym membership costs.
