#+hugo_base_dir: ../
#+date: <2020-07-04 Sat>
#+hugo_tags: essay skills reality
#+hugo_categories: essay
#+TITLE: Antifragile Skills

  Skills that increase in value with time

  This is yet another idea that's been brewing in my head for a while. I've been looking for a word for skills that improve with time. I'm not talking about compounding as the increase with time is not a constant percentage. The example I have in mind is for skills that "level up" due to repeated use and that remain useful for the future. Such skills benefit from improvement due to constant use as well as being tinkered with to solve real problems.

  In the book [[https://www.goodreads.com/book/show/13525945-so-good-they-can-t-ignore-youge][So Good They Can't Ignore You]], Cal Newport talks about how, for many people, job happiness improves with time as their competence in the job improves with time. This has been my experience as well where constant use of a certain skill set allowed me to both solve real problems as well as improve in the skills being used. However, I've found that it's only through constantly pushing your boundaries (i.e tinkering and experimenting) that you can maintain this growth.

  An example of a skill that grows with use can be seen in the difference between [[https://startingstrength.com/article/training%5Fvs%5Fexercise][training and exercise]]. For most people, exercise does not lead to growth. You remain where you started. With training on the other hand, you push your body to reach higher levels of achievement. This means that the time invested in training allows you much greater abilities in the future compared to the same time invested in exercise.

  Another example could be the choice of tools you use. For me, investing in Emacs has been pretty useful as it allowed me to solve real problems as well as improve in the skill itself. Any future understanding or tinkering improves my Emacs-fu further thus allowing me to target an increasing class of problems.

  An important consideration for these skills is that they have to be applicable across a [[file:multi-use-skills.org][large number of domains]], be constantly used, and allow unbounded improvement with time.

  I'm still clarifying this idea in my head so I expect my understanding and importance of this concept to change in the future. Nevertheless, it's been a useful idea when deciding the amount of time to invest in skills.
