#+hugo_base_dir: ../
#+date: <2018-10-27 Sat>
#+hugo_tags: books review gaming
#+hugo_categories: books
#+TITLE: Book Review: Masters of Doom

* Review
  So, I recently read Masters of Doom by David Kushner and thought I'd post my book review here. I also hope to make this a regular thing.

  [[https://www.goodreads.com/book/show/222146.Masters_of_Doom][Masters of Doom]]

  As someone who used to play a ton of video games and who got into programming making or hacking them, this was an enjoyable, nostalgic experience. Written in dramatic fashion, yet technically not too demanding, this book takes you through the evolution of pc gaming, the rise of an entire sub-culture, and the molding of art, bleeding-edge tech, and storytelling in the birth of doom. It's the story of 2 immensely talented people, their successes, and the differences that ripped them apart amidst the rise of a multi-billion dollar industry. I'd recommend this for anyone who's spent way too many hours gaming or playing Dungeons and Dragons.
