#+hugo_base_dir: ../
#+date: <2020-06-22 Mon>
#+hugo_tags: books review scifi
#+hugo_categories: books
#+TITLE: Book Review: Flowers for Algernon

  [[https://www.goodreads.com/book/show/36576608-flowers-for-algernon][Flowers For Algernon]]

  I came to know of this book from Gwern's [[https://www.gwern.net/Drug-heuristics][The Algernon Argument]].

  Charlie is a mentally challenged individual who lives a life of ignorant bliss though he is mistreated and made fun of by his "friends". Despite the challenges of the society around him, he desperately wants to be smarter and enrolls in reading and writing classes as a 30 year old. The story starts here as he is selected for an experiment to increase human intelligence.

  The story then follows the exploding of his intelligence leading him to truly understand the nature of his situation and relationships. Through a series of journal entries, we see his rise to a super intelligence as he attempts to piece together his reality. We learn about the early childhood abuse by a mother who could not understand nor accept him. The writings of this awakening mind paint a heartbreaking picture of how society treats the intellectually deficient as subhuman. Later, through his own work, he finds that this process rots the brain and that just as he rose, he will soon fall, and die.

  This second part was very painful to read. This tortured mind reflects on its own demise, unable to bear the thought of being pitied by society. Before he loses his intelligence, he attempts to connect with his family, meeting with, and talking to his sister. With this understanding of his past and acceptance, he overcomes his demons and finds peace and love for a few golden days with the woman he loved, his special-ed teacher.

  Alas, we come to the last few days of this great mind, clawing at the intellectual pleasures it knows it cannot pursue, as it rages and pushes people away. The ending sees Charlie returning to his old life and the changes he caused in the people around him. Full disclosure: I was bawling my eyes out at the end.

  From the success of the movie (Charly), the house episode (Ignorance is Bliss), and the Simpsons episode (HOMR), it's easy to see that this idea touched a societal nerve. Modern society is clearly fascinated by the nature of intelligence. Gwern calls intelligence an almost unalloyed good though he (like the book) uses IQ scores as a metric for intelligence. 

  Personally, I don't agree with this model of intelligence (i.e. one based on a linear metric such as IQ; I think it does capture some dimension of it though). Like all complex animal and human traits, I do think that intelligence (which itself is hard to define) varies across individuals. I just think it's multi-dimensional and maybe [[https://en.wikipedia.org/wiki/Partially_ordered_set][partially ordered]]. Anyway, I definitely do not want to get into this argument on the internet :P.

  The story itself is very moving and I read the whole book in one sitting. All in all, 5 stars.
