#+hugo_base_dir: ../
#+date: <2019-05-07 Tue>
#+hugo_tags: books review orwell
#+hugo_categories: books
#+TITLE: Book Review: Down and Out in Paris and London

* Review
  An account of Orwell's time as a homeless man in Paris and London. It was interesting to read about how invisible he became to society (and women in particular). The fellow homeless people he meets were also unique characters in their own right and I suspect many (not all) had mental illnesses of some sort. The law punishes those who stay in one place for too long (Imagine a cop approaching you and telling you to keep walking if you stop and sit somewhere) and they are forced to wander from place to place. There is no rest for them and, though they can spend nights in a homeless shelter (dealing with authority was horrible to read about), they are evicted in the morning forcing them to resume their wandering. This combined with extreme hunger "incentivises" them to latch on to any job they can get, and in Orwell's case, labour 16 hours a day in a dirty hotel for a pittance.
