#+hugo_base_dir: ../
#+date: <2018-10-29 Mon>
#+hugo_tags: books review taleb
#+hugo_categories: books
#+TITLE: Book Review: The Black Swan

* Review
  [[https://www.goodreads.com/book/show/242472.The_Black_Swan][The Black Swan]]
  
  I've always struggled with reading a book that a lot of people constantly talk about. Especially working at GoJek where a lot of people use vocabulary from this book. I'm a bit rebellious that way. About a week ago, I finally got to reading this.

  The Black Swan is definitely a perspective changing book introducing a lot of fresh, powerful ideas and discusses the /nature/ of uncertainty and the limits of knowledge i.e the unknown unknowns. It explains why predicting the future is a fundamentally hard problem and why projects with long timelines have to grapple with the unknown unknowns. Especially when living in a world containing millions of independent-decision making actors. Two actionable strategies which I've found interesting from this book include keeping shorter timelines and the barbell investment strategy.
