#+hugo_base_dir: ../
#+date: <2020-06-18 Thu>
#+hugo_tags: essay complexity taleb
#+hugo_categories: essay
#+TITLE: Complexity

  Complexity: The property of a system having multiple interacting components.

  As a builder of software, complexity is something I fight against daily. The purpose of many of our processes such as Scrum is to attempt to tame complexity in projects with long time scales and myriad moving parts where [[https://en.wikipedia.org/wiki/Murphy%27s_law][Murphy]] lurks. Interestingly, in the talk, [[https://www.youtube.com/watch?v=oytL881p-nQ][Simple Made Easy]], Rich Hickey points out that the word root for "complex" sprang from braided hair.
 
  Complexity, thus, is a property of a system that arises out of its components interacting in multiple ways. Organic systems such as humans and other animals have numerous interacting components which puts a limit on our ability to understand them. This is probably the result of the process of natural selection being unlimited by complexity unlike human endeavors.

  Cities are another example of complex systems built over other organic, complex systems (i.e. humans). The number of interacting components and scale makes cities into complex entities that resist planning and visibility. Hence, as Jane Jacobs points out in [[https://www.goodreads.com/book/show/30833.The_Death_and_Life_of_Great_American_Cities][The Death and Life of Great American Cities]], efforts at city planning are often disastrous. The best cities are often those that grow organically and are governed bottom up.
  
  One important feature of complex systems is the lack of opacity they offer to entities outside it. Thus, as Taleb mentions, the iatrogenesis arising out of city planning, medicine, and foreign intervention. In [[https://www.goodreads.com/book/show/20186.Seeing_Like_a_State][Seeing like a state]], James Scott points out that the first task for rulers was the conquest of legibility. The need to understand more about the entities they govern, often hindered by numerous local customs, rules, measurement systems, naming schemes etc.

  Finally, I have a pet theory that the rise of human intelligence arose out of overcoming complexity. More generally, that the increasing intelligence of any species was selected for by the increasing complexity of their environment. Thus, I think, the high social size of our species and the exploding complexity (due to interacting components) was the driving force for our intelligence. Other properties exclusive to our species such as cooking and tool making were probably a /result/ of our intelligence, not the cause. Ah, a topic for another day.
