#+hugo_base_dir: ../
#+date: <2020-07-05 Sun>
#+hugo_tags: personal fitness diet review
#+hugo_categories: fitness
#+TITLE: Diet and Simplicity

  Over the last few months, I've changed my diet considerably.

  It's based heavily on [[https://twitter.com/Mangan150][PD Mangan's]] book, [[https://gumroad.com/l/dvwGZ][The world's simplest fat loss plan]]. In the book Mangan argues that what we [[file:via-negativa.org][remove]] from our diet is vastly more important than what we add to it. That cutting out all sugar, seed oils, and grains will carry us most of the way to our fat loss goals. Furthermore, he argues that there's [[https://roguehealthandfitness.com/red-meat-is-health-food/][nothing wrong]] with a heavily meat based diet or [[https://roguehealthandfitness.com/higher-cholesterol-associated-with-longer-life/][high cholesterol]] diets.

   My current diet currently consists primarily of meat, eggs, dairy products, and vegetables. I have my first meal of the day at around 11 AM. This includes half a dozen eggs topped with the previous night's dinner and a glass of milk. I skip lunch as breakfast keeps me sated well until late afternoon. This happens because protein is the most [[https://roguehealthandfitness.com/higher-protein-greater-weight-loss/][highly satiating]] macro-nutrient and my breakfast contains about 40 grams of it.

   I eat a cup of yogurt in the evening. If I feel hungry, I'll add some more eggs and milk too. For dinner, I eat one non-vegetarian dish which may include fish, organ meats, chicken, or other meat cooked in butter. I also eat one vegetarian item which is usually some mix of legumes, vegetables, or paneer.

   Yeah, my diet's pretty low on carbs and highly processed foods. Since I [[file:my-sleep-schedule.org][sleep very early]], I end up eating dinner by 6 PM. Thus, I fast for about 17 hours till breakfast the next day though this fluctuates depending on how delayed my breakfast is. On the days I weight train, I eat some boiled eggs as a midnight snack.

   The big change and the simplicity comes from what I avoid. I don't keep any starch-rich foods or sugar at home. Adopting a trick from [[https://www.goodreads.com/book/show/40121378-atomic-habits][Atomic Habits]], I keep track of the days I don't eat sugar. It's formed a chain about 6 months long now. For grains, it's been even longer though I do eat the occasional burger bun. I also avoid tea and coffee.

   In my experience, it's much easier to avoid some foods completely than diet and count calories. One technique that's helped is to taboo certain foods. One of my takeaways from the book [[https://www.goodreads.com/book/show/667203.Purity_and_Danger][Purity and Danger]] is that it's easy for humans to avoid foods that they see as taboo. I've experimented with trying to see foods that contain sugar and processed grain as impure and vile. It makes it easy to avoid it and also forces me to check the ingredients of any food I buy.

   This combined with my excellent culinary skills caused me to lose about 5 kg over a 2 month period. I've not lost any strength as far as I can tell from my weight training routine so the loss should be mostly fat. I might even remove more foods in the future 😄.
