#+hugo_base_dir: ../
#+date: <2020-06-17 Wed>
#+hugo_tags: essay growth direction velocity
#+hugo_categories: essay
#+TITLE: Direction vs Velocity

  In my experience, it's usually been the case that direction is far more important than velocity. Whether it be career changes or project execution, moving fast is wasteful if we're not moving in the right direction. Furthermore, early direction gives us the /option/ to change. Thus it almost always makes sense to include getting feedback as early as possible in any design.
 
  In product development, this is one of the reasons why having an MVP out early is so beneficial. The early feedback that it generates can guide your direction so that you proceed along the right course. Similarly, one reason to have a reference customer is to get early reviews to provide direction. Often the ideal choice of metrics should guide both direction /and/ velocity. i.e. It should give us a feel for both the rate of change as well as the direction of that change.

  In Scrum, weekly review meetings and sprints can be thought of as constructs that provide direction and velocity. Sprint velocity is optimized but the weekly reviews are to be used to correct direction. OKRs too can be thought of as direction providing machinery. Fundamentally they're about setting a clear direction and working towards that whilst keeping the option to change direction based on circumstance.
 
  In cases where the direction is not clear to me, one useful mental model has been to have two extreme modes of thinking. Taleb calls this the barbell strategy. In the first mode, I collect as much information as I can within a limited time frame. In the next, I try to venture out slightly in that direction as fast as possible to collect feedback. Sort of like a minimum viable journey 😄
 
  I find it useful to include direction gathering in any process I undertake. This has given me great benefits in the past. They can be thought of as purchasing some options through spending some project velocity. What you're buying is the option to change direction at an early stage. Based on my past experience, I'm happy to pay the premium on these options.
