#+hugo_base_dir: ../
#+date: <2020-07-19 Sun>
#+hugo_tags: personal goals meta
#+hugo_categories: meta
#+TITLE: Dissonance and Dragons

  Many moons ago, a friend and I started a [[https://en.wikipedia.org/wiki/Dungeons_%26_Dragons][Dungeons and Dragons]] group in Bangalore. We got together a bunch of our friends for weekly evenings exploring the lands of dragons and men. I found that, in the game, the players displayed impressive dissonance between their words and actions. Often, morality would be tossed aside in pursuit of higher ideals.

  In one of our campaigns, our heroes got locked in a barn fighting a demon goat. After winning the gruesome battle, they suspected that they were set up. They angrily approached the farm owner and interrogated her. Finding out that she was innocent, our heroes pondered their next step. Still not fully convinced, they decided to forcibly take her teenage son PyNorth along.

  At this point, as the DM, I was curious about their reasons for kidnapping a teenage kid whilst on a dangerous quest to rid the land of evil. I soon got my answer as a tied up Pynorth was dragged along and forced to do menial tasks. He would often be slapped randomly by the characters for no predictable reason. A few times, he was pushed forward as a guinea pig to check for possible traps on their path.
 
  Eventually, he became the torchbearer for the party. As in, he would literally hold the torch with his bound hands and light the way ahead as the party followed behind him. At this point, they took to calling him Pytorch despite his vocal objections. Yet, every town they visited, our heroes thumped their chests and proudly declared their allegiance to righteousness. Talk about [[https://en.wikipedia.org/wiki/Ludonarrative_dissonance][ludonarrative dissonance]]!

  This is hardly the only instance. In another campaign, our party had just restored a holy artifact to the temple. As they walked out of this sacred ground, they saw a bunch of ruffians loitering around on the street outside. Despite no real provocation from the ruffian's side, our "heroes" launched an all-out attack on them /although they really didn't have to/, killed most of them, took a hostage, tortured him, and then hung his dead body from an oak tree on the temple grounds.

  "Understand the motivations of the players and everything else will follow" is my mantra when DMing. Yet, it was difficult to make sense of this mindless slaughter. The sacrilege of the temple grounds served no purpose, narrative or otherwise. It seemed like the party was a bunch of murderous thugs out to rid the land of evil.

  Sigh. It was fun while it lasted. Apart from the extreme dissonance, I found the power of a shared narrative to weave a collaborative world to be truly amazing. I hope to share more such stories after our games resume.
