#+hugo_base_dir: ../
#+date: <2020-06-24 Wed>
#+hugo_tags: essay taleb mental-model
#+hugo_categories: essay
#+TITLE: Fearlessness

  The lack of fear and/or the courage to overcome it.
 
  I've been trying to be less afraid over the last year. I've been stepping out of my shell more and embracing rejection. To me courage starts from being fearless in daily life and in the decisions I make. This has meant being completely honest as well as putting myself in more vulnerable situations. In this regard, I can feel that, like all second-order and third-order effects, the actions I take condition my brain.

  In the book [[https://www.goodreads.com/book/show/13588356-daring-greatly][Daring Greatly]], Brene Brown talks about the courage needed to be vulnerable. Vulnerability requires extreme honesty and the courage to overcome shame. I can relate to this. I, like many people, used to have a fear of public speaking. It was a fear of public vulnerability that held me back for a long time. Even when writing, I used to be scared of putting things up that were not perfect. To a large degree, perfection is the enemy of good.
 
  According to Taleb, courage is the original virtue. The latin word *virtu* implies courage. In [[https://www.goodreads.com/book/show/36064445-skin-in-the-game][Skin in the Game]], he claims that it is the only /true/ virtue in the sense that it cannot be faked. Complete honesty and other virtues require great courage foremost and an utter lack of fear.

  In his great talk, [[https://jamesclear.com/great-speeches/you-and-your-research-by-richard-hamming][You and your research]], Richard Hamming talks about how you /need/ to be fearless to execute in the real world. "I ain't scared of nuthin" he quotes Shannon, a man he clearly admires for the intellectual audacity he had in tackling problems. Fear will constrain you otherwise.
 
  This has definitely been my experience at work where some of my greatest gains were made when I became more fearless in executing tasks. Whether it be overcoming analysis paralysis or moving fast and breaking things, being more fearless has been rewarding for me personally.

  The ideas I'm trying out currently include trying to be completely honest with others and myself as well as following through with ideas I believe in. I hope I can look back at this post in a year having accomplished some real changes in life.
