#+hugo_base_dir: ../
#+date: <2020-06-26 Fri>
#+hugo_tags: essay systems mental-model
#+hugo_categories: essay
#+TITLE: Feedback and Magic

  I often find the effect of feedback on many systems magical. Whether it real world systems or my own life, feedback often leads to constant change which accumulates. This process often ends up changing the [[file:direction-vs-velocity.org][direction and velocity]] of growth significantly.

  Cities are a wonderful example of this in the real world. As Jane Jacobs points out in [[https://www.goodreads.com/book/show/30833.The_Death_and_Life_of_Great_American_Cities][The death and life of great American cities]], the vitality of a city depends on the continuous use of a city which creates a feedback loop of facilities to serve people which in turn attracts more people to use the city. Going back further, the emergence of the industrial revolution can be viewed as a result of a feedback loop of demand for coal creating a feedback loop of cross-serving, interconnected technologies[fn:1].

  In my own life, I've found this to be true in smart note taking. The act of trying to elaborate concepts that you've learnt in your own words, forces you to address your blind spots and gives you instant feedback about your understanding of the content. This, like other endeavors where you get instant feedback, allows you to progress rapidly in skill.

  Similarly I've found falsifying any project ideas as fast as fast as possible to be an excellent strategy. John Carmack proposes such an approach in his [[https://www.youtube.com/watch?v=dSCBCk4xVa0][Antifragile Idea Generation]] talk at Facebook. Collecting feedback from other humans is a very valuable approach in this regard. This is especially the case for hackathon and business ideas where the act of pitching your ideas and getting feedback is critical. Often it gives you insights into your unknown unknowns.

  Similarly feedback in negative systems can often be terrible. For example, I procrastinate when I feel overwhelmed. When I do procrastinate, I lose time and increase time pressure further thus creating a negative feedback loop. This makes it critical to break out of such negative feedback loops as early as possible.

  I'm constantly amazed by the power of feedback loops and their applicability across domains both biological or otherwise. The end results, whether it be in city vitality, global economies, skill acquisition, or ideation, seem magically transformative to me.
 
* Footnotes

[fn:1] Faster, Better, Cheaper in the history of manufacturing ([[https://www.goodreads.com/book/show/29527358-faster-better-cheaper-in-the-history-of-manufacturing][link]])
