#+hugo_base_dir: ../
#+date: <2020-08-18 Tue>
#+hugo_tags: essay skills mental-model human-mental-model memory
#+hugo_categories: essay
#+TITLE: Memory Training and Sania Mirza

  Ever since I read Joshua Foer's [[https://www.goodreads.com/book/show/6346975-moonwalking-with-einstein][Moonwalking with Einstein]], I've had a fascination with memory training. 

  In the book, he mentions that the method of loci (a.k.a the memory palace technique) has been in use for at least 2000 years. According to legend, it started in a banquet hall in ancient Greece. When the host stepped out to address a couple of visitors, the roof collapsed killing everyone in the hall. As grieving family members assembled, they couldn't identify their loved ones among the mangled remains. The host, remembering the position of each person around the banquet table, then led everyone to their loved ones. Thus was born the method of loci.

  A gruesome origin story, it serves to highlight 2 aspects of our memory. That we're very good at remembering vivid imagery and spatial information. Combining this with an encoding scheme allows us to store and recall great amounts of information. I'd imagine that this featured prominently in how humans stored information before the medium of the written word became cheap enough. So I thought it's worth trying it out.

  I started by trying to memorize a deck of cards. Adding it to my [[file:the-inevitability-of-variability.org][morning routine]] and spending about 10 minutes a day for 2 months, I got to memorizing half a deck of cards in about 2 minutes. Neat! I noticed a [[file:feedback-and-magic.org][feedback loop]] of increased confidence arising from seeing my performance improve so measurably which served to keep me motivated. By now I bet you're wondering how Sania Mirza is related to any of this. Is this click bait? The answer will shock you!

  It turns out that for best results, the artifacts in your memory palace have to be very vivid. For, ahem, historical reasons, my brain recognizes Sania Mirza easily. To give you an example, let's say I had to remember the following series of cards: 2 of spades, 5 of spades, and 2 of dice. Using the [[https://artofmemory.com/wiki/Major_System#Assigning_sounds_to_digits][major system]] as my encoding scheme, I combine the first letter of the suit (S for spades) and the consonant from the major mode (Ex: /n/ for 2) to use /Sa/-/n/-ia Mirza for 2 of spades. Thus the previous series can be imagined as Sania Mirza selling dynamite (/l/ being the consonant for 5).

  The fact that this works so well fascinates me. However, I've found that there's still a lot left to do beyond just the technique. As I continued training, I found that my visualization skills, encoding and decoding speed, focus, and confidence in my memory palace all improved. Of course, memorizing cards is hardly useful in the real world. The next part would be to try to use this for more real-world purposes. Recently, I've been experimenting with using this for mental [[file:book-review-how-to-take-smart-notes.org][note-taking]] thus eliminating the notebook I carry around. I'm currently re-re-reading [[https://www.goodreads.com/book/show/13530973-antifragile][Antifragile]] and using that as a [[https://www.nateliason.com/blog/self-education][sandbox]] to apply this. I've found that this requires a lot of focus when reading. Perhaps I'll write more about this in a future post.
