#+hugo_base_dir: ../
#+date: <2020-07-06 Mon>
#+hugo_tags: essay mental-model taleb
#+hugo_categories: essay
#+TITLE: Oh Lindy

  The Lindy effect states that the future life-expectancy of a non-perishable (Ex: ideas, techniques, jobs, books, technology etc) is proportional to its current age.

  Yet another mental model from [[https://twitter.com/nntaleb/][Taleb]]'s [[https://www.goodreads.com/series/164555-incerto][incerto]] series, the Lindy effect has that effect where once you hear about it, you start seeing it everywhere.

  It springs from the fact that time is the ultimate test. /Anything/ can happen in the future. Ideas/Techniques can be lost or lose their value. Something new can replace them. That which withstands the vagaries of time for a longer duration has more staying power. Thus the duration it has survived so far is an indication of its staying power and reflects its expected future life expectancy. Sort of like a reverse aging.

  This also ties in with the Popperian idea of every theory being falsifiable. i.e. Every theory should bear the risk of being falsified. The easier it is to falsify, the greater the risk it bears and the better the theory. Thus those that survive for a long time show some staying power and can be expected to age in reverse, i.e. the longer it exists and the easier it is to falsify, the stronger the theory. Something like old and bold is gold 😅.

  Now that I know it, I see it in a lot of places. An example would be writings on human nature in the past. Whether it be an ancient roman poet's words that "We are interested in others when they are interested in us"[fn:1] or how Plato wrote about those who "feast on their own thoughts"[fn:2] both of which I can relate to.
 
  This also applies to technology. I was surprised by the antiquity of railroads (2000 years ago, ancient Greece) and the assembly line (600 years ago, Venetian ship building)[fn:3], things I thought were more recent innovations stemming from first-principles thinking.
 
  Lindy's been a very useful mental model and one that ties in well with [[file:via-negativa.org][Via-Negativa]]. It's also interesting to think about in relation to biology, genetics, and software. Perhaps, I'll write about these in a future post.

* Footnotes

[fn:3] [[https://www.goodreads.com/book/show/29527358-faster-better-cheaper-in-the-history-of-manufacturing][Faster, Better, Cheaper in the history of Manufacturing]]

[fn:2] [[https://www.goodreads.com/book/show/27036528-ego-is-the-enemy][Ego is the Enemy]]

[fn:1] [[https://www.goodreads.com/book/show/4865.How_to_Win_Friends_and_Influence_People][How to Win Friends and Influence People]]
