#+hugo_base_dir: ../
#+date: <2020-07-01 Wed>
#+hugo_tags: essay career
#+hugo_categories: essay
#+TITLE: On Career Capital

  Career Capital: What you gain from working on a career of your choice

  I've been reading a couple books on career guidance recently. Apart from the importance of competence, autonomy, and relatedness in picking an ideal job, another interesting idea I picked up was the idea of choosing professions that offer you career capital.
 
  What is career capital? In [[https://www.goodreads.com/book/show/33229792-80-000-hours][80,000 hours]], Todd argues that career capital involves gaining competence, connections, credentials, and capital. Competence refers to the skill-sets that you gain and their ability to [[file:multi-use-skills.org][generalize across domains]]. Connections are measured by the quality of the people you meet and work with. Credentials act as a strong signal to all future opportunities and the amount of capital earned affects how much runway you have if/when you quit.
 
  What you gain from this is the optionality to change your career in the future. This is an important consideration as we don't /know/ how our future values will change. While competence and credentials help you get your foot in the door of opportunities, connections are interesting in their ability to increase your knowledge boundary and serendipity. Career capital allows us the choice of picking a problem we care about or take advantage of any future positive black swan.

  I find career capital to be an interesting idea and something well worth keeping in mind especially for people entering the job market.
