#+hugo_base_dir: ../
#+date: <2020-07-10 Fri>
#+hugo_tags: essay motivation goals personal
#+hugo_categories: personal
#+TITLE: On Motivation

  A topic I've struggled with my whole life, motivation is the /reason/ we engage in any activity.

  For a long time, I've used the "carrot and stick" approach, as described in the book [[https://www.goodreads.com/book/show/6452796-drive][Drive]], to motivate myself to get through less-desirable pursuits. The idea is to have something I desire at the end of a pursuit whilst running away from something I fear. This got me through school as I studied out of fear of failing and the desire for high grades. To be fair, school wasn't very challenging. However, this system collapsed entirely in college. I just wasn't motivated to study the subjects being taught. However, this didn't mean I wasn't learning.

  Throughout college and my professional life, I had no trouble being motivated to study interesting stuff or work on interesting problems both at work and home. A lot of it was my desire for novelty and hard puzzles. Some of it was about working with friends and colleagues to build something cool. It was a fickle thing, this motivation. I had to nurture it. It's easy to get worked up over an idea but staying motivated till it's shipped is a Hard Problem.

  I [[file:on-tinkering.org][tinkered]] with many systems over the years, Todo lists, GTD, Scrum etc till I got a fairly reliable process going that allowed me to be motivated and work on longer timescale projects. At work, it was tied to my sense of autonomy and impact. At home, it was tied to both impact and challenge. From these experiences, I've realized that I like to work on projects which are hard, high-impact, and where I have control (and hence responsibility).

  Forced to work from home due to the pandemic, I've had to battle with my demons yet again. [[file:my-sleep-schedule.org][Custom schedules]], the [[https://jamesclear.com/how-to-stop-procrastinating][2-minute-rule]] from [[https://www.goodreads.com/book/show/40121378-atomic-habits][atomic habits]], and [[file:day-of-rest.org][forced rest]] were useful allies. Of course, I'm not at the end of history, and much may lurk in the unknown unknowns of the future. Some other bottleneck may arise. Or new strategies. As always, time will tell.
