#+hugo_base_dir: ../
#+date: <2020-08-31 Mon>
#+hugo_tags: motivation productivity personal systems
#+hugo_categories: personal
#+TITLE: On Productivity

  It's been almost 2 weeks since the last time I wrote a post. Looking back, my productivity in the last week had taken a hit. Anyhow, thought I'd might as well use this as an opportunity to write about what productivity means to me and how I try to be productive at work and life.

  In the book [[https://www.goodreads.com/book/show/30227731-high-performance-habits][High Performance Habits]], Brendon Burchard points out that productivity is often highly correlated with satisfaction at work. Going by the countless books already written on it, I think most people acknowledge this, at least intuitively. This also aligns with my experience at work and life. My happiest days were those where I got a lot of high-impactful stuff done. Through a lot of [[file:on-tinkering.org][tinkering]] over the past few years, some general themes emerged which have stuck around more than others.

  One of the most helpful ideas is better prioritization and focus. Taking some time at the start of the day and week to identify the highest impact problem I can work on and then switching to focusing solely on tackling that helped a lot. I've found focus to be a real multiplier in getting things done. A closely related idea to this is to [[https://wiki.c2.com/?MakeItWorkMakeItRightMakeItFast][Make It Work Make It Right Make It Fast]], or what I call multi-pass hacking. In the first pass, the sole aim is to get it working. In the second pass, make it easier to maintain. In the third pass, optimize. For me, this helped enforce the right priority and focus at each stage. I've also found this useful in tackling problems in multiple domains outside programming.
  
  Similarly, one idea that helped to better maintain this process was to set up a system of work. For me this meant demarcating different kinds of work by reserving a certain number of continuous hours for [[https://www.goodreads.com/book/show/25744928-deep-work][deep work]] while keeping the rest for a mixture of collaboration, work, or rest. Through a combination of calendar-fu and personal [[file:my-sleep-schedule.org][schedules]], I was able to block off large amounts of contiguous time for myself where I could get a significant amount done. Since creative work /requires/ [[file:the-inevitability-of-variability.org][variability]], fixed schedules just won't work. Thus some days I would work less, using the remaining for rest and collaboration while on others, I would work for long stretches of time.

  Finally, the idea that's helped optimize this process is the combination of [[file:Fearlessness.org][fearlessness]] and ownership. They also align well with the previous points. Being more fearless when tackling projects helped me move a lot faster. Having a sense of ownership injected the right amount of paranoia when moving fast. Personally, I've also found it /incredibly/ [[file:on-motivation.org][motivating]] when carrying the trust of others.

  In all probability, a lot of these are specific to me and my history. They're also complex topics on their own and deserve their own posts. Nonetheless, I think some would find this relatable and helpful.
