#+hugo_base_dir: ../
#+date: <2020-07-11 Sat>
#+hugo_tags: essay motivation goals process personal list
#+hugo_categories: personal
#+TITLE: Pandemic Life Tactics

  I've been tinkering with my processes trying to execute efficiently during this pandemic. Here are some tactics that I've found particularly helpful.

* Routine
  Having a daily morning routine helps me with getting my non-negotiable daily tasks done every day. Of course, creative endeavors and their [[file:the-inevitability-of-variability.org][accompanying variability]] cannot fit in with the determinism needed of a morning routine so I've learned to put only non-creative tasks here. It's like having a creativity budget in the allotted morning hours. Moreover, I've found this to be contingent on the quality and consistency of my sleep.
 
* Sleep
  This was a big one. It's important to have high quality, consistent sleep. I've found that getting back to my desired [[file:my-sleep-schedule.org][sleep schedule]] after interruptions is better than trying to suppress the variability of life. Furthermore, having a bi-phasic sleep helped with maintaining energy levels at 2 different times of the day.
 
* Focus
  It's what you [[file:via-negativa.org][remove]] from your focus that helps more than any new tactic. Keeping distractions away (especially my phone) starting work using the 2 minute rule, and [[file:day-of-rest.org][forced rest]] helped me start and maintain focus for a longer duration of time. Anecdotally, I've found meditating to be a powerful tool to notice when I start being distracted.

* Fasting
  Related to [[file:black-and-white-barbells.org][black and white thinking]], the idea is to have periods of fasting and feasting and nothing in between. This is true of socializing as well. Switching between lone work and group video calls/games with friends and family is definitely a better strategy for fun and focus.

  There are many more but these are the things that have had the highest impact. Since the pandemic doesn't seem like it'll get over any time soon, consider this list a WIP.
