#+hugo_base_dir: ../
#+date: <2020-08-09 Sun>
#+hugo_tags: essay mental-model human-mental-model
#+hugo_categories: essay
#+TITLE: Relative Thinking

  Relative thinking is the phenomenon where humans (and other animals) are more sensitive to relative differences rather than absolute differences. The idea is that humans are wired to see the world in relation to what is nearby in time and space. That, in a way, everything has an accompanying context which affects how we perceive reality.

  Recently, I'd finished the book [[https://www.goodreads.com/book/show/43190966-refactoring-ui][Refactoring UI]] where the author talked about the concept of a visual hierarchy i.e. emphasizing different elements in relation to each other. Using the principle allows us to direct human attention through differences in position, emphasis, and spacing of related elements. Design can thus be seen as an art of directing attention.

  Another application of this is in the power of contrast, an oft-quoted mental model of Charlie Munger, best highlighted in the fable of the [[https://en.wikipedia.org/wiki/Boiling_frog][Boiling Frog]]. In this story, a frog that is suddenly put into boiling water will immediately jump out. However, if it's placed in cool water which is gently heated, the frog will remain in the water until it dies. A real world example of this is how many humans end up staying in careers where they grow very slowly. Many of them would not have chosen the same option if they could initially contrast themselves against the position they would be in 2 years time.

  This is also the reason for the emotions many of us feel when we browse social media as we compare our lives against what we see online. It is often the success of a friend that forces us to take stock of our own situation. Similar reasons hold for many of our biases such as anchoring where we judge options against nearby options as well as the constant increase in price during a social auction.

  We can also use this to our advantage. One technique I've found useful is to surround yourself with smart and ambitious people. I've found this helpful in breaking out of contrast traps and finding the motivation to pursue many activities. Similarly, an alternative to the low feelings of social media browsing could be trying to see how many people would be willing to trade lives with you (For Ex: by strolling through a hospital) though I've personally not tried this.

  Overall, I've found this to be a powerful mental model of how humans think with applications across design, sales, marketing, and motivation. I hope I can learn more about this by applying it in the real world. Let's see.
