#+hugo_base_dir: ../
#+date: <2020-07-02 Thu>
#+hugo_tags: talks review ideation mental-model taleb
#+hugo_categories: talks
#+TITLE: Talk: Antifragile Idea Generation

  [[https://www.youtube.com/watch?v=dSCBCk4xVa0][Link to YouTube video]]

  This was an internal engineering talk given by John Carmack at Facebook in 2015.

  Though the is by by John Carmack, I liked the gems dropped by Kent Beck who introduced him.
  - "Sometimes, the best way to be smart is not to be smart at all"
  - "Young developers don't understand how deeply great developers care"

  In this talk, Carmack discusses his process of ideation. I thought that some of the ideas mentioned could be re-framed using mental models I previously discussed.

  He starts off by saying that it's /very important/ to have lots of ideas. It's always better to have to [[file:via-negativa.org][drop]] ideas than struggle to have them. Well, how do you have lots of ideas? Carmack suggests exposing yourself to lots of stimulus. That this could be the source of a lot of ideas especially if you can link them together.

  He says it's important to enjoy the high when you get an idea and then try to bust the idea as fast as possible. I'd say the reason it's important to enjoy the high when you get an idea is to condition your brain to enjoy the ideation process.
 
  Thus when ideating, the first thing to think about is how to falsify the idea. This rapid falsification imposes a selection pressure on your ideas such that those that survive are robust to some degree and are strengthened through antifragility. The process of falsification also gives you instant negative [[file:feedback-and-magic.org][feedback]] on your ideas and, like any skill, you get better at ideation through repeated use and feedback.

  This gives you an [[file:on-asymmetries.org][asymmetry]] where you enjoy the highs and limit the lows of trying out bad ideas. This process can also be seen through the lens of [[file:black-and-white-barbells.org][expansion-contraction]] where we first focus on generating lots of ideas, and then switch to aggressively pruning them.

  On ideas, he says that, improvements by at least a factor of 4 are where things /start/ to get interesting for him.

  Finally, he talks about how it's important to test out ideas. Having ideas and not busting them causes them to become pet ideas. That you will not be as harsh as necessary on them. Thus it's important to be /able/ to test out your ideas in the real world quickly.

  I found this talk /extremely/ interesting. Currently, this is the only video on his [[https://www.youtube.com/channel/UCTtZ908OWKkGNOYLwkWttRw][YouTube channel]]. Let's hope he does more such talks.
