#+hugo_base_dir: ../
#+date: <2020-06-30 Tue>
#+hugo_tags: talks review
#+hugo_categories: talks
#+TITLE: Talk: You and your research

  [[https://www.youtube.com/watch?v=a1zDuOPkMSw][Link to YouTube video]]

  In this talk, Hamming discusses his success and what he's learnt over his career. To start, he talks about the nature of success itself. He reasons that success is easy to maintain but hard to get. It is far easier to succeed when you're already successful than when you're not. Well, how do you be successful? Do outstanding things he says. Essentially, it's hard to be successful without taking some risks.
 
  On the role of luck, he states, as many before him, that luck favors the prepared mind. It is not enough to be lucky, he says, you have to be able to take advantage of it. In a way, receptiveness to positive black swans is not always passive. In many situations, /you/ have to play an active part in riding them.

  Another topic he touches on is the bare [[file:Fearlessness.org][fearlessness]] you need to execute in the real world. "I ain't scared of nuthin" he quotes Shannon, a man he clearly admires. He says that audacity and fearlessness are attributes you /need/ to get things done and that fear will constrain you otherwise.

  Hamming then asks "If what you're working on is not important, then why are you working on it?". This question forces us to be active participants in life and not just passively live through life. It's important to _work on the right problems at the right time_ and to be /able/ to do that. As he later says, "The person who works on the right problem at the right time in the right way wins.". Nothing else counts. Fortunately, there are "A million races being run". It depends on us to work on the right problems. Thus this also means that we need to take time to decide the right problems to work on. In his case, it was Friday afternoons.

  The most important problems are also decided by whether they can be attacked, argues Hamming. This again, relates to working on the right problem. He stresses on the need for a good work ethic. "Whatever you do, do it well" he says.

  Relentlessly question the problem you're working on. Sometimes what happens to be a defect may turn out to be an asset. This often means solving/seeing something that many people missed, A key ingredient of great men according to Hamming.

  On communication, he says that it's equally important to be able to communicate your ideas through multiple channels; Written, Oral, and Casual.

  On dealing with systems and people, he argues that first and foremost, it's important not to blame the system. You constantly want to keep an open mind and be receptive to other ideas. Interacting with people and ideas is an asymmetric opportunity and you want more of that.

  He goes on to talk about how change is essential to progress. All progress requires change and it is foolish to expect otherwise. If you want greatness, you have to do something about it. The onus is on you to demonstrate greatness and not on other people to see it in you. Asking people who've found success in their own lives, they said it was "Better than wine, women, and song put together".

  I'd found this talk to be a wake-up call when I first heard it. It made me ask some tough questions about myself and about my direction in life. Do give it a watch if you haven't. It generalizes well across many domains.
