#+hugo_base_dir: ../
#+date: <2020-06-27 Sat>
#+hugo_tags: essay work habits randomness
#+hugo_categories: essay
#+TITLE: The Inevitability of Variability

  I've come to accept the inevitability and necessity of variability in life and work.

  In [[https://www.goodreads.com/book/show/38315.Fooled_by_Randomness][Fooled By Randomness]], Taleb argues that we should welcome randomness. Not try to suppress it. Though he argued from a different standpoint (i.e. embracing the serendipity of life), I've come to accept it coming from a different perspective though I do understand the serendipity argument having witnessed it in my own life.

  Over the last few years, I've tried living life to a schedule and I've concluded that it's impossible. Sooner or later, if you engage in creative or uncertain work, you /will/ break your schedule. To be fair, my epistemic certainty on this is based solely on my experience but in my defense, I've been trying to conquer variability for at least the past 4 years using a multitude of strategies.

  I've found that it's /very hard/ to tackle hard problems within a fixed deadline. As a rough heuristic, anything important and meaningful requires solving these kinds of hard problems where the unknown unknowns loom constantly near. I've definitely found this to be the case when building something new or tackling the complexity of large-scale projects at work.

  In my case, the strategies I tried included trying to limit work hours to 8 hours a day. And an additional 3-4 hours to work on side projects. The thing is, these things always require more time than you plan for. Especially in the modern workplace where your work life often bleeds outside the confines of the 9-5 (or 11-7 in my case) and projects have long timelines.

  In [[https://www.goodreads.com/book/show/6278270-the-principles-of-product-development-flow][Principles of Product Development Flow]], Reinertsen argues that new product development and innovation /require/ variability and that high utilization rates amplify variability. If I think about myself as a product development company of one, then what this means is that the higher my utilization rate (percentage of time used for some task) is, the more amplified will be the variability in my process.

  My current strategy is a multi-pronged strategy of habit routines and keeping spare time buffers. I have a morning habit stack routine (inspired by the idea from [[https://www.goodreads.com/book/show/40121378-atomic-habits][atomic habits]]) where I do many of the must-dos of my life (Ex: Writing, Meditation, Workout etc). This enables me the advantages of structure (hitting my daily goals), whilst allowing me to be prepared for variability and to benefit from serendipity during the rest of the day.

  Another thing I do is to keep at least 3-4 hours of free time available after work. This way, if deadlines are at risk of being exceeded or unexpected issues occur, I can use this extra capacity. Over a long time period, I can look at the amount of extra time I'm putting in to get an idea of the average time spent. (Though this is just an idea at this point as I've not been doing this.)

  I've learnt a lot from my struggles with variability. I reckon I'll continue to grow and learn more as I uncover new problems.
