#+hugo_base_dir: ../
#+date: <2020-06-21 Sun>
#+hugo_tags: meta thoughts
#+hugo_categories: meta
#+TITLE: Thoughts on Dot Asterisk

  Part of the reason why I started writing this blog was to explore ways of sharing my knowledge and to practice finding my voice when writing. My goals remain the same but the past week of writing has caused me to think more deeply about what I hope to accomplish with Dot Asterisk. Today I want to share some ideas about the process of expression and how I want to do it.

  I feel writing alone might not be the most effective way of expressing myself. Visualizations definitely help here. Humans are much better at processing visual information rather than text. [[file:on-asymmetries.org][Previously]], I've played around with using GraphViz on this site. Grammar of graphics frameworks like Vega have piqued my intereset too. For now, I think GraphViz serves me quite well though Vega might be an interesting option for when I need much more flexibility or expressiveness.
 
  Another way I think I could improve content is by using presentations. I'd been reading and applying [[https://www.goodreads.com/book/show/30089737-better-presentations][Better Presentations]] for technical presentations at work. I'm only a bit in but it's opened my eyes to how presentation is fundamentally /different/ from writing. Using story-telling and structured information flow to maintain attention allow humans to be engaged while consuming information. This ties in with visualizations as a way to optimize for the human consuming content rather than the one producing it. Presentation frameworks like [[https://github.com/yjwen/org-reveal][Reveal.js]] look interesting in this regard.

  It would be remiss not to mention one of the ways modern websites are fundamentally different from previous media. Namely, the more direct ways users can /engage/ with the medium being consumed such as through commenting, following, and social discussions. This again highlights another aspect of how humans can help in the information process; through discussions and feedback. It's on my to-do list to open this blog up for comments and I'll do that when I have enough time and confidence.

  Finally, a technical note on how I run Dot Asterisk. This blog is set up using Hugo. I use Emacs and Org Mode to craft my posts which are then exported using the lovely [[https://ox-hugo.scripter.co/][ox-hugo]] package. This allows me the ability to control the exporting process to a large degree. As an example, I hacked around with my org export code to export my notes to [[https://notes.ppsreejith.net][notes.ppsreejith.net]] in the /exact/ way I want (I use [[https://github.com/org-roam/org-roam][org-roam]] for note taking). I've enjoyed this ability to hack around and fine-tune the exporting process. This process also allowed me to learn more about Hugo and Org Mode internals.

  Ah, many things to do. Too many priorities. I really hope I can try out other ways of expressions this year. Maybe I can find some time to clean up the design of this blog too.
