#+hugo_base_dir: ../
#+date: <2020-06-13 Sat>
#+hugo_tags: meta goals writing
#+hugo_categories: meta
#+TITLE: On Writing Again

  "Shipping beats perfection"

  I've decided to start writing again. It may not be perfect but I think the habit of penning down, distilling, and sharing thoughts is a valuable exercise.
 
  One big influence is the book [[https://www.goodreads.com/en/book/show/34507927][How to Take Smart Notes]] by Sonke Ahrens. As the book suggests, writing is thinking. I'd been taking and [[https://notes.ppsreejith.net][sharing]] notes regularly on the content I consume. Compiling and sharing these notes is the next step.
 
  These notes should allow me to keep a list of ideas handy. My current strategy is to pick topics from these notes that excite me the most. I hope that excitement as metric will motivate me to continue writing, keep my articles interesting, and act as a north start when deciding what to write about.
 
  I'll probably start with book reviews, publishing them here and on my [[https://www.goodreads.com/user/show/20228885-sreejith-puthanpurayil][goodreads]] page. I've built a backlog of books I haven't updated yet. This should be a convenient starting point.

  As always, time will tell and reality will be the judge.
