#+hugo_base_dir: ../
#+date: <2020-06-23 Tue>
#+hugo_tags: essay taleb mental-model
#+hugo_categories: essay
#+TITLE: Via Negativa

  Via Negativa: Through removal rather than addition.

  Another powerful mental model that I came to know from Taleb's books, this idea suggests that in reality, many things can be improved by removal rather than addition.

  This is closely related to the idea of inversion. i.e For extremely difficult questions like happiness, rather than asking "What do I add to gain happiness?", it's often better to start from a position of "What do I remove to reduce unhappiness?"
 
  The same holds true for what you choose to focus on in life. In the book [[https://www.goodreads.com/book/show/25744928-deep-work][Deep Work]], Cal Newport mentions that it's what you say no to that decides your success. Accomplishing anything meaningful requires saying no to almost everything else except that what matters. For many individuals and companies focusing on metrics, less might be better. i.e rather than adding more metrics, its often better to start from a position of "Which metrics can be removed?"
 
  Expansion-contraction is another mental model that is tied to both Via Negativa and the Barbell mental model of which the contraction part is fundamentally a process of filtering, i.e. Via Negativa. For example, when evaluating career options, it makes sense to first collect as many options as possible before aggressively filtering them. This is because filtering and removal is often a far easier problem to solve. In a [[file:on-asymmetries.org][previous article]], I'd mentioned Haskell's QuickCheck which also uses this strategy.
 
  Natural selection too can be thought of as operating this way. The fitness of a species improves through the process of generating new genetic combinations and weeding out the unfit.
 
  Even when writing this article, I use a form of expansion-contraction, by aggregating notes from different related topics, and then removing that which I don't need. This is far more efficient for me than attempting to write only relevant information. An example to visualize would be to think of sculpture where the process of removing that which is not needed results in the final art.

  I find Via Negativa a useful mental model in my daily life. Eliminating distractions, bad foods, bad habits, and bad people have led to a marked improvement in the quality of my own life.
