#+hugo_base_dir: ../
#+date: <2020-09-12 Sat>
#+hugo_tags: personal skills human-mental-model memory
#+hugo_categories: personal
#+TITLE: Zettelkasten and Memory Palaces

  I'd written about my [[https://notes.ppsreejith.net][note taking system]] and my efforts at [[file:memory-training-and-sania-mirza.org][memory training]] in previous posts.  As mentioned, I'd been using a memory palace to replace using a notebook when taking notes [[https://en.wikipedia.org/wiki/Zettelkasten][Zettelkasten]] style. It's been about 1 month now that I'd been trying this out while re-re-reading [[https://www.goodreads.com/book/show/13530973-antifragile][Antifragile]]. In this post, I'll share what I learnt from this endeavor.

  The first thing I noticed is the increased amount of focus needed when reading and storing memories. Storing something in my memory palace reliably still requires a lot of concentration if I am to do it reliably. The way I do it requires me to store the context around the concept so I often end up storing complex concept chains in my memory palace.

  This brings me to the second change I noticed which is that I pause and summarize a lot more when reading now. Storing the context around noteworthy concepts forces me to regularly pause and progressively summarize when reading. Previously, when using a notebook, when something strikes me as worth noting down, I take some time to explain it in my own words and then proceed to write it down. When using my memory palace, I find myself adding an additional step of summarizing the context outside the note to create more memorable scenes that I can remember reliably.

  Finally, after doing this for a while, I noticed an increase in the amount of concepts I hold in my head while trying to grok an idea. This is because in addition to the stuff I did with a notebook (i.e. self explanations and linking to other zettels), I also need to summarize the surrounding context and encode it into a memorable, linked scene to completely note down a scene. Often I discuss with my inner voice, repeating it to myself in different ways to really grok the idea as well as link it to other concepts.

  When I started, I felt pretty tired with the greatly increased amount of effort involved. It still feels much more tiring than using a notebook though it's become a lot easier. I definitely feel like I've improved my memory skills as this feels a lot more "real world" than memorizing decks of cards. Of course, time will tell if I'm able to stick with this practice.

  Recently, I've also started using this to store any interesting stray thoughts as well as an inbox for my GTD setup. I feel that my memory access speed and latency can be improved further so I'll focus on improving these metrics in my memory palace. This would involve focusing on the speed with which I create visualizations for complex, real world information. Perhaps I can share my stories in a future post.
